"""rename address

Revision ID: 07442953acf7
Revises: 4e76ba68d7e7
Create Date: 2023-12-05 11:11:29.383085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07442953acf7'
down_revision = '4e76ba68d7e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','location',new_column_name='address')
    # ### end Alembic commands ###
