"""rename departments

Revision ID: 4e76ba68d7e7
Revises: feabe624eb02
Create Date: 2023-12-05 10:45:43.093895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e76ba68d7e7'
down_revision = 'feabe624eb02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department','departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
